//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectTemp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorrectTemp.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Shop is unique; a company which is headquartered in Sri Lanka with 48 manufacturing facilities placed across 15 countries, with design locations placed in key style centres across the globe and with over 79,000 people involved in its operation..
        /// </summary>
        public static string About_firstline {
            get {
                return ResourceManager.GetString("About_firstline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seamlessly integrated supply chain that is balanced to perfection with the organisation’s strategically placed design houses gives knowledge, the means and the speed to delivery that is demanded by the industry..
        /// </summary>
        public static string About_secondline {
            get {
                return ResourceManager.GetString("About_secondline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Item.
        /// </summary>
        public static string Exclusive_Item {
            get {
                return ResourceManager.GetString("Exclusive_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Bags.
        /// </summary>
        public static string For_Bags {
            get {
                return ResourceManager.GetString("For_Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Kids.
        /// </summary>
        public static string For_Kids {
            get {
                return ResourceManager.GetString("For_Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Men.
        /// </summary>
        public static string For_Men {
            get {
                return ResourceManager.GetString("For_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Women.
        /// </summary>
        public static string For_Women {
            get {
                return ResourceManager.GetString("For_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE SHIPPING.
        /// </summary>
        public static string Free_Ship {
            get {
                return ResourceManager.GetString("Free_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 DAYS MONEY BACK.
        /// </summary>
        public static string MoneyBack {
            get {
                return ResourceManager.GetString("MoneyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        public static string New_Arrivals {
            get {
                return ResourceManager.GetString("New_Arrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Shoes.
        /// </summary>
        public static string On_Shoes {
            get {
                return ResourceManager.GetString("On_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string Our_Products {
            get {
                return ResourceManager.GetString("Our_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string Our_Services {
            get {
                return ResourceManager.GetString("Our_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75% off.
        /// </summary>
        public static string SeventyFive_off {
            get {
                return ResourceManager.GetString("SeventyFive_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site map.
        /// </summary>
        public static string Site_map {
            get {
                return ResourceManager.GetString("Site_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORT 24/7.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% off.
        /// </summary>
        public static string twentyfive {
            get {
                return ResourceManager.GetString("twentyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string Useful_Links {
            get {
                return ResourceManager.GetString("Useful_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
    }
}
