//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartID { get; set; }
        public string itemID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> total { get; set; }
        public string username { get; set; }
        public string productName { get; set; }
    }
}
