//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Price { get; set; }
        public string ItemAvailability { get; set; }
        public string ItemCategory { get; set; }
    }
}
