//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wlist
    {
        public int wishlistID { get; set; }
        public string itemID { get; set; }
        public string username { get; set; }
        public string itemName { get; set; }
        public Nullable<int> itemPrice { get; set; }
    }
}
